import { BadgeDefinition } from '../types/achievement';

export const BADGE_DEFINITIONS: BadgeDefinition[] = [
  // Streak Badges
  {
    id: 'streak_3',
    title: 'Spark of Momentum',
    description: 'Maintained a 3-day consecutive execution streak.',
    category: 'streak',
    tier: 'bronze',
    icon: 'Zap',
    conditionDescription: 'Reach a 3-day streak',
    evaluate: (s) => s.maxStreak >= 3,
    progress: (s) => ({
      current: Math.min(3, s.maxStreak),
      target: 3,
      percent: Math.min(100, Math.round((s.maxStreak / 3) * 100)),
    }),
  },
  {
    id: 'streak_7',
    title: 'Weekly Titan',
    description: 'Completed a full 7-day unbroken chain of consistency.',
    category: 'streak',
    tier: 'silver',
    icon: 'Flame',
    conditionDescription: 'Reach a 7-day streak',
    evaluate: (s) => s.maxStreak >= 7,
    progress: (s) => ({
      current: Math.min(7, s.maxStreak),
      target: 7,
      percent: Math.min(100, Math.round((s.maxStreak / 7) * 100)),
    }),
  },
  {
    id: 'streak_14',
    title: 'Fortress of Habit',
    description: 'Reached 14 consecutive days of relentless discipline.',
    category: 'streak',
    tier: 'gold',
    icon: 'Shield',
    conditionDescription: 'Reach a 14-day streak',
    evaluate: (s) => s.maxStreak >= 14,
    progress: (s) => ({
      current: Math.min(14, s.maxStreak),
      target: 14,
      percent: Math.min(100, Math.round((s.maxStreak / 14) * 100)),
    }),
  },
  {
    id: 'streak_30',
    title: 'Master of Will',
    description: 'A monolithic 30-day streak. Your neural pathways have locked in.',
    category: 'streak',
    tier: 'diamond',
    icon: 'Award',
    conditionDescription: 'Reach a 30-day streak',
    evaluate: (s) => s.maxStreak >= 30,
    progress: (s) => ({
      current: Math.min(30, s.maxStreak),
      target: 30,
      percent: Math.min(100, Math.round((s.maxStreak / 30) * 100)),
    }),
  },

  // Completion Count Badges
  {
    id: 'tasks_1',
    title: 'Day One',
    description: 'Completed your very first task. The journey begins.',
    category: 'completion',
    tier: 'bronze',
    icon: 'CheckCircle2',
    conditionDescription: 'Complete 1 task',
    evaluate: (s) => s.totalCompleted >= 1,
    progress: (s) => ({
      current: Math.min(1, s.totalCompleted),
      target: 1,
      percent: Math.min(100, Math.round((s.totalCompleted / 1) * 100)),
    }),
  },
  {
    id: 'tasks_10',
    title: 'Decathlete',
    description: 'Checked off 10 total task executions.',
    category: 'completion',
    tier: 'silver',
    icon: 'TrendingUp',
    conditionDescription: 'Complete 10 total tasks',
    evaluate: (s) => s.totalCompleted >= 10,
    progress: (s) => ({
      current: Math.min(10, s.totalCompleted),
      target: 10,
      percent: Math.min(100, Math.round((s.totalCompleted / 10) * 100)),
    }),
  },
  {
    id: 'tasks_50',
    title: 'Half-Century Club',
    description: '50 successful task completions logged.',
    category: 'completion',
    tier: 'gold',
    icon: 'Target',
    conditionDescription: 'Complete 50 total tasks',
    evaluate: (s) => s.totalCompleted >= 50,
    progress: (s) => ({
      current: Math.min(50, s.totalCompleted),
      target: 50,
      percent: Math.min(100, Math.round((s.totalCompleted / 50) * 100)),
    }),
  },
  {
    id: 'tasks_100',
    title: 'Century of Greatness',
    description: '100 tasks executed with uncompromising precision.',
    category: 'completion',
    tier: 'diamond',
    icon: 'Crown',
    conditionDescription: 'Complete 100 total tasks',
    evaluate: (s) => s.totalCompleted >= 100,
    progress: (s) => ({
      current: Math.min(100, s.totalCompleted),
      target: 100,
      percent: Math.min(100, Math.round((s.totalCompleted / 100) * 100)),
    }),
  },

  // Focus & Study Badges
  {
    id: 'focus_60',
    title: 'Deep Diver',
    description: 'Logged over 60 minutes of uninterrupted study or focus time.',
    category: 'focus',
    tier: 'bronze',
    icon: 'Clock',
    conditionDescription: 'Log 60 minutes of focus time',
    evaluate: (s) => s.totalFocusMinutes >= 60,
    progress: (s) => ({
      current: Math.min(60, s.totalFocusMinutes),
      target: 60,
      percent: Math.min(100, Math.round((s.totalFocusMinutes / 60) * 100)),
    }),
  },
  {
    id: 'focus_300',
    title: 'Monk Mode',
    description: 'Accumulated 5 hours (300 minutes) of deep cognitive focus.',
    category: 'focus',
    tier: 'silver',
    icon: 'Brain',
    conditionDescription: 'Log 300 minutes of focus time',
    evaluate: (s) => s.totalFocusMinutes >= 300,
    progress: (s) => ({
      current: Math.min(300, s.totalFocusMinutes),
      target: 300,
      percent: Math.min(100, Math.round((s.totalFocusMinutes / 300) * 100)),
    }),
  },
  {
    id: 'focus_1200',
    title: 'Hyperfocus Sovereign',
    description: '20 hours of high-leverage deep work recorded.',
    category: 'focus',
    tier: 'diamond',
    icon: 'Sparkles',
    conditionDescription: 'Log 1,200 minutes of focus time',
    evaluate: (s) => s.totalFocusMinutes >= 1200,
    progress: (s) => ({
      current: Math.min(1200, s.totalFocusMinutes),
      target: 1200,
      percent: Math.min(100, Math.round((s.totalFocusMinutes / 1200) * 100)),
    }),
  },

  // Special & Strategy Badges
  {
    id: 'target_1',
    title: 'Strategic Visionary',
    description: 'Set a multi-month target to anchor your daily habits.',
    category: 'special',
    tier: 'silver',
    icon: 'Compass',
    conditionDescription: 'Have at least 1 active target goal',
    evaluate: (s) => s.totalGoals >= 1,
    progress: (s) => ({
      current: Math.min(1, s.totalGoals),
      target: 1,
      percent: s.totalGoals >= 1 ? 100 : 0,
    }),
  },
  {
    id: 'reflection_3',
    title: 'Stoic Philosopher',
    description: 'Recorded at least 3 evening reflections and energy scores.',
    category: 'special',
    tier: 'gold',
    icon: 'BookOpen',
    conditionDescription: 'Log 3 daily reflections',
    evaluate: (s) => s.totalReflections >= 3,
    progress: (s) => ({
      current: Math.min(3, s.totalReflections),
      target: 3,
      percent: Math.min(100, Math.round((s.totalReflections / 3) * 100)),
    }),
  },
];
